// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           48
// Total number of exported functions:  50

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    digiko_swap
    (
        init => init
        upgrade => upgrade
        createPair => create_pair
        deletePair => delete_pair
        setPairActive => set_pair_active
        setPairFee => set_pair_fee
        updatePairTokenA => update_pair_token_a
        updatePairTokenB => update_pair_token_b
        ownerRemoveLiquidity => owner_remove_liquidity
        ownerClaimFees => owner_claim_fees
        mint => mint
        depositPendingA => deposit_pending_a
        depositPendingAKlv => deposit_pending_a_klv
        depositPendingB => deposit_pending_b
        depositPendingBKlv => deposit_pending_b_klv
        finalizeLiquidity => finalize_liquidity
        withdrawPendingA => withdraw_pending_a
        withdrawPendingB => withdraw_pending_b
        withdrawPendingAll => withdraw_pending_all
        removeLiquidity => remove_liquidity
        claimLpFees => claim_lp_fees
        swapAtoB => swap_a_to_b
        swapBtoA => swap_b_to_a
        swapKlvToB => swap_klv_to_b
        swapKlvToA => swap_klv_to_a
        getReserves => get_reserves
        getPairInfo => get_pair_info
        getPairInfoExtended => get_pair_info_extended
        getTotalShares => get_total_shares
        getOwnerFees => get_owner_fees
        getLpPosition => get_lp_position
        getPendingDeposits => get_pending_deposits
        getLpCount => get_lp_count
        isLp => is_lp
        getLpList => get_lp_list
        getLpInfo => get_lp_info
        getAllLpInfo => get_all_lp_info
        getRegisteredPairs => get_registered_pairs
        getAllPairIds => get_all_pair_ids
        getNextPairId => get_next_pair_id
        getPairCreator => get_pair_creator_view
        isPoolEmpty => is_pool_empty
        getPairsByCreator => get_pairs_by_creator
        findPairsByTokens => find_pairs_by_tokens
        getPendingUserCount => get_pending_user_count
        canDeletePair => can_delete_pair
        previewFirstLiquidity => preview_first_liquidity
        previewFirstPrice => preview_first_price
        quoteSwap => quote_swap
        quoteSwapReverse => quote_swap_reverse
    )
}
